name: CI
on:
  push:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.1.0'
      - run: git submodule init
      - run: git submodule update
      - run: npm install
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
        with:
          commitMessage: 'Deploy to GitHub Pages (Actions: ${{ github.sha }})'